### ISSUE TITLE
音质音效在启用AutoSEffSwitch后崩溃, 无法进入设置页面 | HyperOS 2

### ISSUE THREAD

**Issue by hank9999** [HChenX/AutoSEffSwitch#1]
设备：小米15 (dada)
版本：HyperOS 2.0.23.2 Beta (安卓15 2024-11-01)
LSPosed：1.9.2（7086）- Zygisk
Zygisk Next：1.2.4（445-031a64c-release）

错误日志：
```log
11-24 18:40:01.982  6017  6017 I LSPosed-Bridge: Crash unexpectedly: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.HEADSET_PLUG flg=0x40000010 (has extras) } in c.e@da497c3
11-24 18:40:01.982  6017  6017 I LSPosed-Bridge: Caused by: java.lang.SecurityException: Permission Denial: not allowed to send broadcast miui.intent.action.ACTION_AUDIO_EFFECT_REFRESH from pid=6017, uid=10173
```
完整日志：https://pastebin.com/e3AdnwfJ

HyperOS 1 时正常使用（

感谢您创作如此好用的模块

**Comment by HChenX** [comment]
暂无OS2设备哦

**Comment by HChenX** [comment]
后面会适配的

**Comment by hank9999** [comment]
> 后面会适配的

辛苦了

**Comment by hank9999** [comment]
![image](https://github.com/user-attachments/assets/4aa7e861-c31b-463f-b747-e71901d928de)
好像是 安卓15 OS2 换了广播ID

**Comment by hank9999** [comment]
#2

**Comment by HChenX** [comment]
OS2到账了，解锁后开始适配

**Comment by hank9999** [comment]
> OS2到账了，解锁后开始适配

好耶！我捣鼓了好几天，也没发现为什么杜比切换不了😭

**Comment by HChenX** [comment]
> > OS2到账了，解锁后开始适配
> 
> 好耶！我捣鼓了好几天，也没发现为什么杜比切换不了😭

是不是在音质音效界面发现一直不能切换。
其实是因为他刷新的时候触发bug了，把非用户操作给判断了，然后又执行了打开杜比的逻辑（）

**Comment by hank9999** [comment]
> > > OS2到账了，解锁后开始适配
> > 
> > 好耶！我捣鼓了好几天，也没发现为什么杜比切换不了😭
> 
> 是不是在音质音效界面发现一直不能切换。
> 其实是因为他刷新的时候触发bug了，把非用户操作给判断了，然后又执行了打开杜比的逻辑（）

我在音质音效界面外连上耳机，打开音质音效也还是杜比（）

**Comment by HChenX** [comment]
> > > > OS2到账了，解锁后开始适配
> > > 
> > > 好耶！我捣鼓了好几天，也没发现为什么杜比切换不了😭
> > 
> > 是不是在音质音效界面发现一直不能切换。
> > 其实是因为他刷新的时候触发bug了，把非用户操作给判断了，然后又执行了打开杜比的逻辑（）
> 
> 我在音质音效界面外连上耳机，打开音质音效也还是杜比（）

tg私聊我一下

**Comment by HChenX** [comment]
下载最新版本

**Comment by hank9999** [comment]
感谢aaa
